### ISSUE TITLE
:3

### ISSUE THREAD

**Issue by PatrickSantoZZ** [nmods/no-more-censor#1]
dont work on EU client P88.5 (german client)
autofahrer / automatikfahrer / fuck tested. dont work. still cencored( idk why the first two words are cencored that normal german words lul)

**Comment by nmods** [comment]
It should work now. figured i wasn't taking the case of the characters into account.

![TERA_2020-01-20_19-23-13](https://user-images.githubusercontent.com/45678960/72746310-7587a080-3bba-11ea-939c-b230ddfc5372.png)
